version: '3'

services:
  game-lobby:
    container_name: game-lobby
    build: .
    command: npm run dev
    depends_on:
      - postgres
    volumes:
      - .:/usr/game-lobby
    networks:
      - game-lobby-network
    ports:
      - '3333:3333'

  postgres:
    container_name: postgres
    image: postgres:12-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
    networks:
      - game-lobby-network
    ports:
      - '5432:5432'

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    volumes:
      - .:/usr/pgadmin/
    ports:
      - 15432:80
    networks:
      - game-lobby-network
    links:
      - 'postgres:pgsql-server'
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}

  redis:
    container_name: redis
    image: bitnami/redis:latest
    restart: always
    volumes:
      - .:/usr/redis-data
    ports:
      - '6379:6379'
    environment:
      ALLOW_EMPTY_PASSWORD: 'no'
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
    networks:
      - game-lobby-network

networks:
  game-lobby-network:
    driver: bridge
